import './globals.css';
//import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

//const inter = Inter({ subsets: ['latin'] })
//commenting this out cus it might cause problems

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}

/*
body used to have this className, not sure it's useful to us tho
<body className={inter.className}>
*/