import './globals.css';
import {useLocale} from 'next-intl';
import {notFound} from 'next/navigation';
//import { Inter } from 'next/font/google';
//import Navbar from '../../components/Navbar';
//import Footer from '../../components/Footer';

//const inter = Inter({ subsets: ['latin'] })
//commenting this out cus it might cause problems

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: any
}) {
  //get the current locale with the useLocale hook
  const locale = useLocale();
 
  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        {children}
      </body>
    </html>
  )
}

/*
params has type any for now, i know it's an array of something(but not sure if they are strings or what)

body used to have this className, not sure it's useful to us tho
<body className={inter.className}>

<Navbar />
{children}
<Footer />
*/